# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt.xci
# IP: The module: 'clk_div_cmt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_cmt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt.xci
# IP: The module: 'clk_div_cmt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: x:/Data/ap_codes/Lab3_demo/Lab3_demo.srcs/sources_1/ip/clk_div_cmt/clk_div_cmt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div_cmt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
